config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  get "users/login_form"
  post "users/login"
  post "users/logout"
  get "users/:id/active" => "users#active", as: "users_active"
  patch "users/:id/active_update" => "users#active_update", as: "users_active_update"

  get "users/:id/password_edit" => "users#password_edit", as: "users_password_edit"
  patch "users/:id/password_update" => "users#password_update", as: "users_password"

  get "users/password_forget" => "users#password_forget", as: "users_password_forget"
  post "users/email_where" => "users#email_where", as: "users_email_where"
  get "users/:id/password_forget_edit" => "users#password_forget_edit", as: "users_password_forget_edit"
  patch "users/:id/password_forget_update" => "users#password_forget_update", as: "users_password_forget_update"

  get "users/:id/likes" => "users#like_index", as: "users_likes_index"
  get "sounds/day_rank"
  get "sounds/week_rank"
  get "sounds/month_rank"
  resources :users do
  	resources :like_users, only:[:create, :destroy]
  end
  resources :sounds do
  	resources :comments, only:[:create, :destroy]
    resources :like_sounds, only:[:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :user_id, presence: true
	validates :sound_id, presence: true
	validates :comment, length: {maximum: 140}

	belongs_to :sound
	belongs_to :user
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
	def edit
	end

	def update
	end

	def create
	end

	def destroy
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :not_current_user
	before_action :not_user_active
	before_action :set_variables

	def create
		@comment = Comment.new(user_id: @current_user.id, sound_id: params[:sound_id], comment: params[:comment][:comment])
		if @comment.save
			redirect_to sound_path(params[:sound_id])
			flash[:success] = "コメントを投稿しました。"
		else
			flash.now[:danger] = "投稿に失敗しました。"
			render sound_path(params[:sound_id])
		end
	end

	def destroy
		@comment = Comment.find_by(id: params[:id])
		if @current_user.admin == true
			@comment.destroy
			redirect_to sound_path(params[:sound_id])
			flash[:danger] = "コメントを削除しました。"
		elsif @current_user.id != @comment.user_id
			redirect_to root_path
        	flash[:danger] = "権限がありません。"
        else
			@comment.destroy
			redirect_to sound_path(params[:sound_id])
			flash[:danger] = "コメントを削除しました。"
		end
	end

	private

	def set_variables
	  @sound = Sound.find(params[:sound_id])
	  @id_name = "#like-link-#{@sound.id}"
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<% if @current_user %>
		<div class="col-md-4 col-sm-12 col-xs-12">
			<div class="row user_edit_box margin">
				<%= form_for(@comment, data: { remote: true }, url: sound_comments_path(@sound.id)) do |f| %>
					<div class="form-group margin">
						<%= f.text_area :comment, class: "form-control", placeholder: "140文字以内"  %>
					</div>
					<div class="form-group">
							<%= f.submit "コメント", class: "btn btn-info margin"  %>
						</div>
				<% end %>
			</div>
		</div>
	<% else %>
		<div class="col-md-3 col-sm-12 col-xs-12"></div>
	<% end %>

	<div class="col-md-6 col-sm-12 col-xs-12">
		<% @sound.comments.each do |comment| %>
			<div class="row user_edit_box margin">
				<div class="col-md-1"></div>
				<div class="col-md-3 col-sm-3 col-xs-3">
					<div class="comment_box margin">
						<%= link_to user_path(comment.user.id) do %>
							<%= attachment_image_tag comment.user, :image, fallback: "/no_image.jpg", class: "comment_image"%>
							<ul>
								<li><%= comment.user.name %></li>
							</ul>
					<% end %>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-6">
					<p class="margin1"><%= simple_format(comment.comment) %></p>
				</div>
				<div class="col-md-1 col-sm-2 col-xs-2">
					<%if @current_user %>
						<% if comment.user_id == @current_user.id || @current_user.admin == true %>
							<%= link_to "削除", sound_comment_path(@sound.id, comment.id), method: :delete, class: "btn btn-danger comment_btn"%>
						<% end %>
					<% end %>
				</div>
				<div class="col-md-1 col-sm-2 col-xs-2"></div>
			</div>
		<% end %>
	</div>
	<div class="col-md-1"></div>
</div>