config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  get "users/login_form"
  post "users/login"
  post "users/logout"
  get "users/:id/active" => "users#active", as: "users_active"
  patch "users/:id/active_update" => "users#active_update", as: "users_active_update"

  get "users/:id/password_edit" => "users#password_edit", as: "users_password_edit"
  patch "users/:id/password_update" => "users#password_update", as: "users_password"

  get "users/password_forget" => "users#password_forget", as: "users_password_forget"
  post "users/email_where" => "users#email_where", as: "users_email_where"
  get "users/:id/password_forget_edit" => "users#password_forget_edit", as: "users_password_forget_edit"
  patch "users/:id/password_forget_update" => "users#password_forget_update", as: "users_password_forget_update"

  get "users/:id/likes" => "users#like_index", as: "users_likes_index"
  get "sounds/day_rank"
  get "sounds/week_rank"
  get "sounds/month_rank"
  resources :users do
  	resources :like_users, only:[:create, :destroy]
  end
  resources :sounds do
  	resources :comments, only:[:create, :destroy]
    resources :like_sounds, only:[:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    validates :user_text, length: {maximum: 200}
    has_secure_password
    attachment :image

    has_many :sounds, dependent: :destroy
    has_many :like_sounds, dependent: :destroy
    has_many :like_user, dependent: :destroy
    has_many :comments, dependent: :destroy
    def self.search(params)
        results = all.order(created_at: :desc)
        results = results.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    	results
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :not_current_user, {only: [:like_index, :edit, :update, :password_edit, :password_update, :destroy]}
	before_action :user_active, {only: [:active, :active_update]}
	before_action :not_user_active, {only: [:like_index, :edit, :update, :password_edit, :password_update, :destroy, :show]}
	before_action :ensure_correct_user, {only: [:like_index, :edit, :update, :password_edit, :password_update, :destroy]}

	def top
	end

	def new
		@user = User.new
	end

	def active
		@user = User.find_by(id: params[:id])
		session[:user_id] = @user.id
	end

	def active_update
		@user = User.find_by(id: params[:id])
		@user.update(user_params)
		redirect_to root_path
		flash[:info] = "アカウント有効化しました。"
	end

	def create
		@user = User.new(user_params)
		if @user.save
			UserMailer.active(@user).deliver_now
			session[:user_id] = @user.id
			redirect_to root_path
			flash[:info] = "送信されたメールからユーザー有効化してください。"
		else
			flash.now[:danger] = "ERROR_※は必須項目です。"
			render :new
		end
	end

	def login_form
	end

	def login
		@user = User.find_by(email: params[:login][:email])
		if @user && @user.authenticate(params[:login][:password])
			session[:user_id] = @user.id
			redirect_to sounds_path
			flash[:success] = "ログインしました。"
		else
			flash.now[:danger] = "ERROR_メールアドレスとパスワードが一致しません。"
			render :login_form
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to root_path
		flash[:info] = "ログアウトしました。"
	end

	def index
		@users = User.search(params)
	end

	def like_index
		users = LikeUser.where(my_id: @current_user.id)
		@users = User.where(id: users.pluck(:user_id))
		sounds = LikeSound.where(user_id: @current_user.id)
		@sounds = Sound.where(id: sounds.pluck(:sound_id))
	end

	def edit
		@user = User.find_by(id: params[:id])
	end

	def password_forget
	end

	def email_where
		if @user = User.find_by(email: params[:email_where][:email])
			@user.password_forget = Time.now
			@user.save
			PasswordForgetMailer.password_forget(@user).deliver_now
			redirect_to root_path
			flash[:info] = "送信されたメールから１時間以内にパスワードを変更してください。"
		else
			flash.now[:danger] = "ERROR_メールアドレスが間違っています。"
			render users_password_forget_path
		end
	end

	def password_forget_edit
		@user = User.find_by(id: params[:id])
		if (Time.zone.now - @user.password_forget) < 1.hours
		else
			redirect_to root_path
			flash[:danger] = "ERROR_有効時間が過ぎています。または変更済みです。"
		end
	end

	def password_forget_update
		@user = User.find_by(id: params[:id])
		if user_params[:password].blank?
			flash.now[:danger] = "パスワードを入力してください。"
			render :password_forget_edit
		else
			if (Time.zone.now - @user.password_forget) < 1.hours
				if @user.update(user_params)
					@user.password_forget = @user.password_forget - 2.hour
					@user.save
					redirect_to root_path
					flash[:info] = "パスワードを変更しました。"
				else
					flash.now[:danger] = "ERROR_パスワードが一致しません。"
					render :password_forget_edit
				end
			else
				redirect_to root_path
				flash[:danger] = "ERROR_有効時間が過ぎています。または変更済みです。"
			end
		end
	end

	def password_edit
		@user = User.find_by(id: params[:id])
	end

	def password_update
		@user = User.find_by(id: params[:id])
		if @user.update(user_params)
			session[:user_id] = nil
			redirect_to root_path
			flash[:info] = "パスワードを変更しました。"
		else
			flash.now[:danger] = "ERROR_パスワードが一致しません。"
			render :password_edit
		end
	end

	def show
		@user = User.find_by(id: params[:id])
		uri_reg = URI.regexp(%w[http https])
		if @user.user_text
			@user.user_text.gsub!(uri_reg) {%Q{<a href="#{$&}">#{$&}</a>}}
		end
	end

	def update
		@user = User.find_by(id: params[:id])
		if @user.update(user_params)
			redirect_to user_path(@current_user.id)
			flash[:success] = "プロフィールを変更しました。"
		else
			flash.now[:danger] = "ERROR_内容を確認してください。"
			render :edit
		end
	end

	def destroy
		@user = User.find_by(id: params[:id])
		@user.destroy
		redirect_to new_user_path
		flash[:danger] = "ユーザーを削除しました。"
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :facebook, :twitter, :instagram, :youtube, :user_text, :active)
	end

	def user_active
    	if @current_user
	    	if @current_user.active == true
	    		redirect_to root_path
	    		flash[:danger] = "すでに有効化されています。"
	    	end
	    end
    end

    def ensure_correct_user
    	if @current_user.admin == true
        elsif @current_user.id != params[:id].to_i
            redirect_to root_path
            flash[:danger] = "ログインしてください。または、権限がありません。"
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/active.html.erb
<div class="container-fluid">
  <div class="row">
  	<h2 class="center margin_top">ユーザー認証</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(@user, url: users_active_update_path(params[:id]) ) do |f| %>
				<h4 class="center">アカウント有効化を押してください。
				</h4>
				<%= f.hidden_field :active, value: true %>
		<div class="row">
			<div class="form-group">
				<%= f.submit "アカウント有効化", class: "btn btn-info margin_top" %>
			</div>
		</div>
			<%end%>
		</div>
	</div>

	<div class="col-md-3 col-sm-3"></div>

  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<%= form_for(@user) do |f| %>
	<div class="col-md-5 col-sm-5 col-xs-12">
			<%= attachment_image_tag @user, :image, :fill, 500, 500, fallback: "/no_image.jpg", class: "show_image"%>
		<%= f.attachment_field :image %>
	</div>
	<div class="col-md-5 col-sm-7 col-xs-12">
		<div class="user_edit_box row">
			<div class="col-md-1"></div>
			<div class="col-md-10  col-sm-12 col-xs-12 margin_top">
				<div class="form-group">
					<label>紹介文</label>
					<%= f.text_area :user_text, class: "form-control", placeholder: "200文字以内" %>
				</div>
				<div class="form-group">
					<label>ニックネームまたはバンド名</label>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				<div class="form-group">
					<label>メールアドレス</label>
					<%= f.text_field :email, class: "form-control"  %>
				</div>
				<div class="form-group">
					<label>facebook</label>
					<%= f.text_field :facebook, class: "form-control" %>
				</div>
				<div class="form-group">
					<label>twitter</label>
					<%= f.text_field :twitter, class: "form-control" %>
				</div>
				<div class="form-group">
					<label>instagram</label>
					<%= f.text_field :instagram, class: "form-control" %>
				</div>
				<div class="form-group">
					<label>You Tube</label>
					<%= f.text_field :youtube, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.submit "編集完了", class: "btn btn-info" %>
				</div>
				<div class="form-group">
					<%= link_to "パスワード変更、退会", users_password_edit_path(params[:id]), class: "btn btn-danger" %>
				</div>
			</div>
			<div class="col-md-1"></div>
		</div>
	</div>
	<%end%>
	<div class="col-md-1"></div>
</div>

app/views/users/index.html.erb
<div class="row user_search_top">
	<div class="col-md-12 col-sm-12 col-xs-12">

			<%= form_with url: users_path, method: :get, local: true do |f| %>
				<%= f.text_field :search, class: "user_search-control", placeholder: "User名を入力してください"  %>
			<div class="search_top1">
	  			<%= f.submit 'Search', name: nil, class: "btn btn-info" %>
	  		</div>
			<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 col-sm-12 col-xs-12 like_index_box">
		<div class="col-md-12 col-sm-12 col-xs-12">
		<h2 style="font-family: Impact;">User List</h2>
		</div>
		<% @users.each do |user| %>
			<div class="index_box">
			<%= link_to user_path(user.id) do %>
				<%= attachment_image_tag user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
				<ul>
					<li><%= user.name %></li>
				</ul>
			<% end %>
			</div>
		<%end%>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/users/like_index.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12 row like_sound">
		<div class="col-md-1"></div>
		<div class="like_index_box col-md-10 col-sm-12 col-xs-12">
			<h2 class="like_index_a"><a>Sounds</a><a class="like_click1">Users</a></h2>
			<% @sounds.each do |sound| %>
				<div class="index_box">
				<%= link_to sound_path(sound.id) do %>
					<%= attachment_image_tag sound.user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
				<ul>
					<li><%= sound.title.truncate(10) %></li>
					<li>M <%= sound.tag1 %></li>
					<li>F <%= sound.tag2 %></li>
					<li>P <%= sound.tag3 %></li>
				</ul>
				<% end %>
				</div>
			<% end %>
		</div>
		<div class="col-md-1"></div>
	</div>

	<div class="col-md-12 col-sm-12 col-xs-12 row like_user">
		<div class="col-md-1"></div>
		<div class="like_index_box col-md-10 col-sm-12 col-xs-12">
			<h2 class="like_index_a"><a>Users</a><a class="like_click2">Sounds</a></h2>
			<% @users.each do |user| %>
				<div class="index_box">
				<%= link_to user_path(user.id) do %>
					<%= attachment_image_tag user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
					<ul>
						<li><%= user.name %></li>
					</ul>
				<% end %>
				</div>
			<% end %>
		</div>
		<div class="col-md-1"></div>
	</div>
</div>

app/views/users/login_form.html.erb
<div class="row">
	<h2 class="center">ログイン</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(:login, url: users_login_path ) do |f| %>
			<div class="col-md-1 col-sm-1"></div>
			<div class="col-md-10 col-sm-10 col-xs-12">
				<div class="form-group">
					<label>メールアドレス</label>
					<%= f.text_field :email, class: "form-control"  %>
				</div>

				<div class="form-group">
					<label>パスワード</label>
					<%= f.password_field :password, class: "form-control"  %>
				</div>

			</div>
			<div class="form-group row">
				<%= f.submit "ログイン", class: "btn btn-info margin_top " %>
			</div>
			<%end%>
			<div class="form-group">
				<%= link_to "パスワードを忘れた方", users_password_forget_path, class: "btn btn-danger" %>
			</div>
			<div class="col-md-1 col-sm-1"></div>
		</div>
	</div>

	<div class="col-md-3 col-sm-3"></div>
</div>

app/views/users/new.html.erb
  <div class="row">
  	<h2 class="center margin_top">新規登録</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(@user) do |f| %>
			<div class="col-md-1  col-sm-1 col-xs-1"></div>
			<div class="col-md-10 col-sm-10 col-xs-10">
				<p style="color:red;">※は必須項目です</p>
				<div class="form-group">
					<label><span style="color:red;">※</span>ニックネームまたはバンド名</label>
					<%= f.text_field :name, class: "form-control" %>
				</div>

				<div class="form-group">
					<label><span style="color:red;">※</span>メールアドレス</label>
					<%= f.text_field :email, class: "form-control"  %>
				</div>

				<div class="form-group">
					<label><span style="color:red;">※</span>パスワード</label>
					<%= f.password_field :password, placeholder: "半角６文字以上", class: "form-control"  %>
				</div>

				<div class="form-group">
					<label><span style="color:red;">※</span>パスワード（確認）</label>
					<%= f.password_field :password_confirmation, class: "form-control"  %>
				</div>
			</div>
			<div class="form-group">
				<%= f.submit "新規登録", class: "btn btn-info margin_top" %>
			</div>

			<%end%>
		</div>
	</div>

	<div class="col-md-3  col-sm-3"></div>

  </div>

app/views/users/password_edit.html.erb
  <div class="row">
  	<h2 class="center margin_top">パスワード変更</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(@user, url: users_password_path(params[:id]) ) do |f| %>
			<div class="col-md-1 col-sm-1"></div>
			<div class="col-md-10 col-sm-10">
				<div class="form-group">
					<label>新しいパスワード</label>
					<%= f.password_field :password, placeholder: "半角６文字以上", class: "form-control"  %>
				</div>
				<div class="form-group">
					<label>新しいパスワード確認</label>
					<%= f.password_field :password_confirmation, class: "form-control"  %>
				</div>

			</div>
			<div class="col-md-1 col-sm-1"></div>

			<div class="form-group row">
				<%= f.submit "パスワード変更", class: "btn btn-info margin_top" %>
			</div>
			<div class="form-group row">
				<%= link_to "退会", user_path(@current_user.id), method: :delete,"data-confirm" => "退会すると全てのデータが削除されますがよろしいですか？" ,class: "btn btn-danger margin_top" %>
			</div>
			<%end%>
		</div>
	</div>

	<div class="col-md-3 col-sm-3"></div>

  </div>

app/views/users/password_forget.html.erb
<div class="container-fluid">
  <div class="row">
  	<h2 class="center margin_top">パスワードを忘れた方</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(:email_where, url: users_email_where_path) do |f| %>
			<div class="col-md-1 col-sm-1"></div>
			<div class="col-md-10 col-sm-10">
				<div class="form-group">
					<label>登録時のメールアドレス</label>
					<%= f.text_field :email, class: "form-control"  %>
				</div>
			</div>
			<div class="col-md-1 col-sm-1"></div>

			<div class="form-group row">
				<%= f.submit "送信", class: "btn btn-info margin_top" %>
			</div>
			<%end%>
		</div>
	</div>

	<div class="col-md-3 col-sm-3"></div>

  </div>
</div>

app/views/users/password_forget_edit.html.erb
<div class="container-fluid">
  <div class="row">
  	<h2 class="center margin_top">パスワード変更</h2>
	<div class="col-md-3 col-sm-3"></div>

	<div class="col-md-6 col-sm-6 col-xs-12">
		<div class="row">
			<%= form_for(@user, url: users_password_forget_update_path(params[:id]) ) do |f| %>
			<div class="col-md-1 col-sm-1"></div>
			<div class="col-md-10 col-sm-10">
				<div class="form-group">
					<label>新しいパスワード</label>
					<%= f.password_field :password, placeholder: "半角６文字以上", class: "form-control"  %>
				</div>
				<div class="form-group">
					<label>新しいパスワード確認</label>
					<%= f.password_field :password_confirmation, class: "form-control"  %>
				</div>

			</div>
			<div class="col-md-1 col-sm-1"></div>

			<div class="form-group row">
				<%= f.submit "パスワード変更", class: "btn btn-info margin_top" %>
			</div>
			<%end%>
		</div>
	</div>

	<div class="col-md-3 col-sm-3"></div>

  </div>
</div>

app/views/users/show.html.erb
<div class="header_top"></div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-5 col-sm-6 col-xs-12">
		<%= attachment_image_tag @user, :image, fallback: "/no_image.jpg", class: "show_image"%>
	<% if @current_user %>
		<% unless @user.id == @current_user.id %>
				<% if LikeUser.find_by(my_id: @current_user.id, user_id: @user.id) %>
					<%= link_to "お気に入り解除", user_like_user_path(@user.id), method: :delete, class: "btn btn-default" %>
				<% else %>
					<%= link_to "お気に入り登録", user_like_users_path(@user.id), method: :post, class: "btn btn-info" %>
				<% end %>
			<% end %>
	<% end %>
	<% if @current_user %>
		<% if @user.id ==  @current_user.id || @current_user.admin == true %>
			<%= link_to "マイページ編集", edit_user_path(@user.id), class: "btn btn-info" %>
		<% end %>
	<% end %>
    </div>
	<div class="col-md-5 col-sm-6 col-xs-12">
		<div class="col-md-12 col-sm-12 col-xs-12 user_show_box center">
			<h2 style="font-family: Impact;">profile</h2>
			<ul>
				<li><%= @user.name %></li>
				<li class="show_text"><%= simple_format(@user.user_text) %></li>
				<li class="li_margin"><%= link_to "facebook",@user.facebook, class: "li_link" %></li>
				<li class="li_margin"><%= link_to "twitter",@user.twitter, class: "li_link" %></li>
				<li class="li_margin"><%= link_to "instagram",@user.instagram, class: "li_link" %></li>
				<li class="li_margin"><%= link_to "you tube",@user.youtube, class: "li_link" %></li>
			</ul>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>
<div class="row" style=" padding-top: 20px;">
	<div class="col-md-1"></div>
	<div class="col-md-10 col-sm-12 show-back">
		<table class="table">
			<thead class="show_link">
				<tr>
					<th>タイトル</th>
					<th>M</th>
					<th>F</th>
					<th>P</th>
					<th></th>
				</tr>
			</thead>
			<% @user.sounds.order(created_at: :desc).each do |sound| %>
			<tbody class="show_link">
				<tr>
					<td><%= link_to sound.title.truncate(10),sound_path(sound.id), class: "show_link" %></td>
					<td><%= sound.tag1 %></td>
					<td><%= sound.tag2 %></td>
					<td><%= sound.tag3 %></td>
					<% if @current_user %>
						<% if @user.id == @current_user.id || @current_user.admin == true %>
							<td>
									<%= link_to "編集", edit_sound_path(sound.id), class: "btn btn-info" %>
							</td>
						<% end %>
					<% end %>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/users/top.html.erb
<div class="row">
	<div class="how_to">
		<h1>How to 1/4</h1>
		<div class="how_to_text">
			<img src="/how_to1.png" class="how_to_image">
			<h2>曲一覧ページではメインタグ、雰囲気、ポイントの３つにセレクトボックスがあります！</h2>
			<button id="next1" class="btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="how_to2">
		<h1>How to 2/4</h1>
		<div class="how_to_text">
			<img src="/how_to2.png" class="how_to_image">
			<h2>今自分が探したい曲に合いそうなものを選択してください！<br>どれか一つだけでも大丈夫！決まったら Search !</h2>
			<button id="next2" class="btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="how_to3">
		<h1>How to 3/4</h1>
		<div class="how_to_text">
			<img src="/how_to3.png" class="how_to_image">
			<h2>気になる曲が見つかればそのページをクリック！<br>あなたの気になる曲がきっと見つかるはずです。</h2>
			<button id="next3" class="btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="how_to4">
		<h1>How to 4/4</h1>
		<div class="how_to_text">
			<img src="/how_to4.png" class="how_to_image">
			<h2>それではOur dropをお試しください。</h2>
			<%= link_to "START", sounds_path, class: "btn btn-info how_link"  %>
		</div>
	</div>

	<div class = "col-md-4 col-sm-4 col-xs-4"></div>
	<div class="col-md-4 col-sm-4 col-xs-4 log">
		<img src="/our_drop-logo.png" class="log_image">
	</div>
	<div class = "col-md-4 col-sm-4 col-xs-4"></div>
</div>
<div class="row">
	<div class = "col-md-2 col-sm-2 col-xs-2"></div>
	<div class = "col-md-8  col-sm-8 col-xs-8">
		<h1 class="log_text">Let's find your favorite music.</h1>
		<div style="text-align: center;">
				<button id="next" class="btn" style="font-family: Impact; font-size: 18px;">How to</button>
	    </div>
		<%= link_to sounds_path do %>
		<p class="top_link">START</p>
		<% end %>
	</div>
	<div class = "col-md-2 col-sm-2 col-xs-2"></div>
</div>