config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  get "users/login_form"
  post "users/login"
  post "users/logout"
  get "users/:id/active" => "users#active", as: "users_active"
  patch "users/:id/active_update" => "users#active_update", as: "users_active_update"

  get "users/:id/password_edit" => "users#password_edit", as: "users_password_edit"
  patch "users/:id/password_update" => "users#password_update", as: "users_password"

  get "users/password_forget" => "users#password_forget", as: "users_password_forget"
  post "users/email_where" => "users#email_where", as: "users_email_where"
  get "users/:id/password_forget_edit" => "users#password_forget_edit", as: "users_password_forget_edit"
  patch "users/:id/password_forget_update" => "users#password_forget_update", as: "users_password_forget_update"

  get "users/:id/likes" => "users#like_index", as: "users_likes_index"
  get "sounds/day_rank"
  get "sounds/week_rank"
  get "sounds/month_rank"
  resources :users do
  	resources :like_users, only:[:create, :destroy]
  end
  resources :sounds do
  	resources :comments, only:[:create, :destroy]
    resources :like_sounds, only:[:create, :destroy]
  end
end

app/models/sound.rb
class Sound < ApplicationRecord
	validates :url, presence: true
	validates :title, presence: true
	validates :user_id, presence: true
	validates :tag1, presence: true
	validates :sound_text, length: {maximum: 200}

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :like_sounds, dependent: :destroy

	def self.search(params)
        results = all.order(created_at: :desc)
        results = results.where('title LIKE ?', "%#{params[:search]}%") if params[:search].present?
	    results = results.where('tag1 LIKE ?', params[:search1]) if params[:search1].present?
 		results = results.where('tag2 LIKE ?', params[:search2]) if params[:search2].present?
	    results = results.where('tag3 LIKE ?', params[:search3]) if params[:search3].present?
    	results
    end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
	before_action :not_current_user, {only: [:edit, :update, :destroy, :new, :create]}
	before_action :not_user_active, {only: [:edit, :show, :update, :destroy, :new, :create]}

	def new
		@sound = Sound.new
	end

	def create
		@sound = Sound.new(sound_params)
		if @sound.url.include?("www.dropbox")
			url = @sound.url.sub(/www.dropbox/,'dl.dropboxusercontent')
			@sound.url = url
			@sound.user_id = @current_user.id
			if @sound.save
				redirect_to sounds_path
				flash[:success] = "投稿しました。"
			else
				flash.now[:danger] = "ERROR_※は必須項目です。"
				render new_sound_path
			end
		else
			flash.now[:danger] = "ERROR_共有用URLを入力してください。"
			render new_sound_path
		end
	end

	def index
		@sounds = Sound.search(params)
	end

	def day_rank
		@sounds = Sound.search(params)
		@like_day = LikeSound.where(created_at: 1.day.ago..Time.now)
		@sounds_day = @like_day.where(sound_id: @sounds.pluck(:id))
		@sound_ranking = @sounds.find(@sounds_day.group(:sound_id).order('count(sound_id) desc').pluck(:sound_id))
	end

	def week_rank
		@sounds = Sound.search(params)
		@like_week = LikeSound.where(created_at: 1.week.ago..Time.now)
		@sounds_week = @like_week.where(sound_id: @sounds.pluck(:id))
		@sound_ranking = @sounds.find(@sounds_week.group(:sound_id).order('count(sound_id) desc').pluck(:sound_id))
	end

	def month_rank
		@sounds = Sound.search(params)
		@like_month = LikeSound.where(created_at: 1.month.ago..Time.now)
		@sounds_month = @like_month.where(sound_id: @sounds.pluck(:id))
		@sound_ranking = @sounds.find(@sounds_month.group(:sound_id).order('count(sound_id) desc').pluck(:sound_id))
	end

	def edit
		@sound = Sound.find_by(id: params[:id])
		if @current_user.admin ==true
		elsif @current_user.id != @sound.user_id
           redirect_to root_path
           flash[:danger] = "権限がありません。"
        end
	end

	def show
		@sound = Sound.find_by(id: params[:id])
		uri_reg = URI.regexp(%w[http https])
		@sound.sound_text.gsub!(uri_reg) {%Q{<a href="#{$&}">#{$&}</a>}}
		response.headers['X-Frame-Options'] = 'ALLOWALL #{@sound.url}'
		@comment = Comment.new
		@comments = Comment.where(sound_id: @sound.id)
	end

	def update
		@sound = Sound.find_by(id: params[:id])
		if @current_user.id != @sound.user_id
           redirect_to root_path
           flash[:danger] = "権限がありません。"
		else
			if params[:sound][:url].include?("www.dropbox")
				if @sound.update(sound_params)
					url = @sound.url.sub(/www.dropbox/,'dl.dropboxusercontent')
					@sound.url = url
					@sound.save
					redirect_to user_path(@current_user.id)
					flash[:success] = "編集完了しました。"
				else
					flash.now[:danger] = "ERROR_内容を確認してください。"
					render :edit
				end
			elsif params[:sound][:url].include?("dl.dropboxusercontent")
				if @sound.update(sound_params)
					url = @sound.url.sub(/www.dropbox/,'dl.dropboxusercontent')
					@sound.url = url
					@sound.save
					redirect_to user_path(@current_user.id)
					flash[:success] = "編集完了しました。"
				else
					flash.now[:danger] = "ERROR_内容を確認してください。"
					render :edit
				end
			else
				flash.now[:danger] = "ERROR_共有用URLを入力してください。"
				render :edit
			end
		end
	end

	def destroy
		@sound = Sound.find_by(id: params[:id])
		if @current_user.admin == true
			@sound.destroy
			redirect_to users_path
			flash[:danger] = "投稿を削除しました。"
		elsif @current_user.id != @sound.user_id
           redirect_to root_path
           flash[:danger] = "権限がありません。"
        else
			@sound.destroy
			redirect_to user_path(@current_user.id)
			flash[:danger] = "投稿を削除しました。"
		end
	end

	private
	def sound_params
		params.require(:sound).permit(:url, :title, :user_id, :tag1, :tag2, :tag3, :sound_text)
	end
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/sounds/day_rank.html.erb
<div class="row">
			<div class="search_top col-md-12 col-sm-12 col-xs-12">
				<%= form_with url: sounds_day_rank_path, method: :get, local: true do |f| %>
					<%= f.text_field :search, class: "search-control", placeholder: "曲名を入力してください"  %>
				<div class="search_top1">
					<label class="margin_right">
						メインタグ
		  				<%= f.select :search1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				雰囲気
		  				<%= f.select :search2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				ポイント
		  				<%= f.select :search3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %>
	  				</label>
	  			</div>
	  			<div class="search_top1">
		  			<%= f.submit 'Search', name: nil, class: "btn btn-info" %>
		  		</div>
				<% end %>
			</div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10  col-sm-12 col-xs-12 like_index_box">
		<div class="col-md-12 col-sm-12 col-xs-12">
		<h2 style="font-family: Impact;">Daily Ranking</h2>
		<%= link_to "All", sounds_path, class: "btn btn-info" %><br>
		<%= link_to "Daily Rank", sounds_day_rank_path, class: "btn btn-default" %>
		<%= link_to "Weekly Rank", sounds_week_rank_path, class: "btn btn-info" %>
		<%= link_to "Monthly Rank", sounds_month_rank_path, class: "btn btn-info" %>
		</div>
		<% @sound_ranking.each do |sound| %>
			<div class="index_box">
			<%= link_to sound_path(sound.id) do %>
				<%= attachment_image_tag sound.user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
				<ul>
					<li><%= sound.title.truncate(10) %></li>
					<li>M <%= sound.tag1 %></li>
					<li>F <%= sound.tag2 %></li>
					<li>P <%= sound.tag3 %></li>
				</ul>
			<% end %>
			</div>
		<%end%>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/sounds/edit.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12">
		<h1 class="center">曲編集</h1>
	</div>
	<div class="col-md-4 col-sm-4"></div>
	<div class="col-md-4 col-sm-4">
		<%= form_for(@sound, url: sound_path(@sound.id)) do |f| %>
			<div class="form-group">
				<label>タイトル</label><br>
				<%= f.text_field :title, class: "form-control"  %>
			</div>

			<div class="form-group">
				<label>drop-box共有用URL</label><br>
				<%= f.text_field :url, class: "form-control"  %>
			</div>

			<div class="form-group">
				<label>メインタグ
				<%= f.select :tag1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %></label>
			</div>

			<div class="form-group">
				<label>雰囲気
				<%= f.select :tag2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %></label>
			</div>

			<div class="form-group">
				<label>ポイント
				<%= f.select :tag3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %></label>
			</div>

			<div class="form-group">
				<label>曲紹介</label><br>
				<%= f.text_area :sound_text, class: "form-control", placeholder: "200文字以内" %>
			</div>

			<div class="form-group">
				<%= f.submit "編集完了", class: "btn btn-info margin_top"  %>
			</div>
			<div class="form-group">
				<%= link_to "削除", sound_path(@sound.id), method: :delete, class: "btn btn-danger"%>
			</div>
		<%end%>
	</div>
	<div class="col-md-4 col-sm-4"></div>
</div>

app/views/sounds/index.html.erb
<div class="row">
			<div class="search_top col-md-12 col-sm-12 col-xs-12">
				<%= form_with url: sounds_path, method: :get, local: true do |f| %>
					<%= f.text_field :search, class: "search-control", placeholder: "曲名を入力してください"  %>
				<div class="search_top1">
					<label class="margin_right">
						メインタグ
		  				<%= f.select :search1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				雰囲気
		  				<%= f.select :search2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				ポイント
		  				<%= f.select :search3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %>
	  				</label>
	  			</div>
	  			<div class="search_top1">
		  			<%= f.submit 'Search', name: nil, class: "btn btn-info" %>
		  		</div>
				<% end %>
			</div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 col-sm-12 col-xs-12 like_index_box">
		<div class="col-md-12 col-sm-12 col-xs-12">
		<h2 style="font-family: Impact;">Post List</h2>
		<%= link_to "Daily Rank", sounds_day_rank_path, class: "btn btn-info" %>
		<%= link_to "Weekly Rank", sounds_week_rank_path, class: "btn btn-info" %>
		<%= link_to "Monthly Rank", sounds_month_rank_path, class: "btn btn-info" %>
		</div>
		<% @sounds.each do |sound| %>
			<div class="index_box">
			<%= link_to sound_path(sound.id) do %>
				<%= attachment_image_tag sound.user, :image, fallback: "/no_image.jpg", class: "like_image"%>
				<ul>
					<li><%= sound.title.truncate(10) %></li>
					<li>M <%= sound.tag1 %></li>
					<li>F <%= sound.tag2 %></li>
					<li>P <%= sound.tag3 %></li>
				</ul>
			<% end %>
			</div>
		<%end%>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/sounds/month_rank.html.erb
<div class="row">
			<div class="search_top col-md-12 col-sm-12 col-xs-12">
				<%= form_with url: sounds_month_rank_path, method: :get, local: true do |f| %>
					<%= f.text_field :search, class: "search-control", placeholder: "曲名を入力してください"  %>
				<div class="search_top1">
					<label class="margin_right">
						メインタグ
		  				<%= f.select :search1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				雰囲気
		  				<%= f.select :search2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				ポイント
		  				<%= f.select :search3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %>
	  				</label>
	  			</div>
	  			<div class="search_top1">
		  			<%= f.submit 'Search', name: nil, class: "btn btn-info" %>
		  		</div>
				<% end %>
			</div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 col-sm-12 col-xs-12 like_index_box">
		<div class="col-md-12 col-sm-12 col-xs-12">
		<h2 style="font-family: Impact;">Monthly Ranking</h2>
		<%= link_to "All", sounds_path, class: "btn btn-info" %><br>
		<%= link_to "Daily Rank", sounds_day_rank_path, class: "btn btn-info" %>
		<%= link_to "Weekly Rank", sounds_week_rank_path, class: "btn btn-info" %>
		<%= link_to "Monthly Rank", sounds_month_rank_path, class: "btn btn-default" %>
		</div>
		<% @sound_ranking.each do |sound| %>
			<div class="index_box">
			<%= link_to sound_path(sound.id) do %>
				<%= attachment_image_tag sound.user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
				<ul>
					<li><%= sound.title.truncate(10) %></li>
					<li>M <%= sound.tag1 %></li>
					<li>F <%= sound.tag2 %></li>
					<li>P <%= sound.tag3 %></li>
				</ul>
			<% end %>
			</div>
		<%end%>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/sounds/new.html.erb
<div class="row">
	<div class="s_how_to">
		<h1>How to 1/6</h1>
		<div class="how_to_text">
			<img src="/sound_new.png" class="how_to_image">
			<h2>まずはあなたのDropboxページにアクセスしましょう。</h2>
			<button class="next1 btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="s_how_to2">
		<h1>How to 2/6</h1>
		<div class="how_to_text">
			<img src="/sound_new2.png" class="how_to_image">
			<h2>共有したい曲の共有ボタンを押します。</h2>
			<button class="next2 btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="s_how_to3">
		<h1>How to 3/6</h1>
		<div class="how_to_text">
			<img src="/sound_new3.png" class="how_to_image">
			<h2>フォームの右下のリンク作成を押します。</h2>
			<button class="next3 btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="s_how_to4">
		<h1>How to 4/6</h1>
		<div class="how_to_text">
			<img src="/sound_new4.png" class="how_to_image">
			<h2>フォームの右下のリンクをコピーを押します。</h2>
			<button class="next4 btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="s_how_to5">
		<h1>How to 5/6</h1>
		<div class="how_to_text">
			<img src="/sound_new5.png" class="how_to_image">
			<h2>コピーは完了しましたか？</h2>
			<button class="next5 btn btn-info">NEXT</button>
		</div>
	</div>
	<div class="s_how_to6">
		<h1>How to 6/6</h1>
		<div class="how_to_text">
			<img src="/sound_new6.png" class="how_to_image">
			<h2>コピーしたURLを貼り付ければOK！</h2>
			<button class="next6 btn btn-info">閉じる</button>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<h1 class="center">新規投稿</h1>
	</div>
	<div class="col-md-4 col-sm-4">
	</div>
	<div class="col-md-4 col-sm-4">
		<p style="color:red;">※は必須項目です</p>
		<%= form_for(@sound) do |f| %>
			<div class="form-group">
				<label><span style="color:red;">※</span>タイトル</label><br>
				<%= f.text_field :title, class: "form-control"  %>
			</div>

			<div class="form-group">
				<label><span style="color:red;">※</span>drop-box共有用URL</label><br>
				<%= f.text_field :url, class: "form-control",placeholder: "https://www.dropbox.com..." %>
			</div>
			<div class="form-group">
				<label><span style="color:red;">※</span>
					メインタグ
					<%= f.select :tag1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %>
				</label>
			</div>

			<div class="form-group">
				<label>
					雰囲気
					<%= f.select :tag2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %>
				</label>
			</div>

			<div class="form-group">
				<label>
					ポイント
					<%= f.select :tag3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %>
				</label>
			</div>

			<div class="form-group">
				<label>曲紹介</label><br>
				<%= f.text_area :sound_text, class: "form-control", placeholder: "200文字以内" %>
			</div>

			<div class="form-group row">
				<div class="col-md-4 col-sm-1"></div>
				<%= f.submit "投稿", class: "btn btn-info col-md-4  col-sm-10 margin_top"  %>
				<div class="col-md-4 col-sm-1"></div>
			</div>

		<%end%>
	</div>
	<div class="col-sm-4"></div>
	<div class="col-md-4 col-sm-12 col-xs-12">
		<div class="form-group">
				<button class="next btn">Dropbox共有用URLの取得の仕方はココ！</button>
		</div>
		<div class="form-group">
			<%= link_to "Dropboxへ行く人はココ！", "https://www.dropbox.com/", target: :blank, class: "btn btn-info" %>
		</div>
	</div>
</div>

app/views/sounds/show.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-5 col-sm-6 col-xs-12">
		<%= attachment_image_tag @sound.user, :image, fallback: "/no_image.jpg", class: "show_image"%>
		<iframe class="iframe" src="<%= @sound.url %>"></iframe>
	</div>
		<div class="col-md-5 col-sm-6 col-xs-12">
		<table class="table">
			<tr>
				<th>曲名</th>
				<td><%= @sound.title %></td>
			</tr>
		</table>
		<table class="table">
			<tr>
				<th>アーティスト名</th>
				<td><%= link_to @sound.user.name, user_path(@sound.user_id) %></td>
				<td></td>
			</tr>
			<tr>
				<th>メインタグ</th>
				<th>雰囲気</th>
				<th>ポイント</th>
			</tr>
			<tr>
				<td><%= @sound.tag1 %></td>
				<td><%= @sound.tag2 %></td>
				<td><%= @sound.tag3 %></td>
			</tr>
		</table>
		<div class="sound_text">
			<p style="padding: 10px;"><%= simple_format(@sound.sound_text) %></p>
		</div>
		<%= render "like_sounds/like", sound_id: @sound.id %>
		<%=link_to "戻る", :back, class: "btn btn-default" %>
	</div>
	<div class="col-md-1"></div>
</div>

<div class="header_top"></div>

<%= render "comments/comment", sound_id: @sound.id %>

app/views/sounds/week_rank.html.erb
<div class="row">
			<div class="search_top col-md-12 col-sm-12 col-xs-12">
				<%= form_with url: sounds_week_rank_path, method: :get, local: true do |f| %>
					<%= f.text_field :search, class: "search-control", placeholder: "曲名を入力してください"  %>
				<div class="search_top1">
					<label class="margin_right">
						メインタグ
		  				<%= f.select :search1, ["男ボーカル", "女ボーカル", "混合ボーカル", "歌なし", "ボーカロイド"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				雰囲気
		  				<%= f.select :search2, ["明るい", "楽しい", "クール", "セクシィ", "優しい", "暗い", "怒り"], :prompt => "選択してください" %>
	  				</label>
		  			<label class="margin_right">
		  				ポイント
		  				<%= f.select :search3, ["ギターかっけぇ", "ベースかっけぇ", "ドラムかっけぇ", "キーボードかっけぇ", "管楽器かっけぇ", "イントロかっけぇ", "弾き語り"], :prompt => "選択してください" %>
	  				</label>
	  			</div>
	  			<div class="search_top1">
		  			<%= f.submit 'Search', name: nil, class: "btn btn-info" %>
		  		</div>
				<% end %>
			</div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 col-sm-12 col-xs-12 like_index_box">
		<div class="col-md-12 col-sm-12 col-xs-12">
		<h2 style="font-family: Impact;">Weekly Ranking</h2>
		<%= link_to "All", sounds_path, class: "btn btn-info" %><br>
		<%= link_to "Daily Rank", sounds_day_rank_path, class: "btn btn-info" %>
		<%= link_to "Weekly Rank", sounds_week_rank_path, class: "btn btn-default" %>
		<%= link_to "Monthly Rank", sounds_month_rank_path, class: "btn btn-info" %>
		</div>
		<% @sound_ranking.each do |sound| %>
			<div class="index_box">
			<%= link_to sound_path(sound.id) do %>
				<%= attachment_image_tag sound.user, :image, fallback: "/no_image.jpg", class: "like_image"%><br>
				<ul>
					<li><%= sound.title.truncate(10) %></li>
					<li>M <%= sound.tag1 %></li>
					<li>F <%= sound.tag2 %></li>
					<li>P <%= sound.tag3 %></li>
				</ul>
			<% end %>
			</div>
		<%end%>
	</div>
	<div class="col-md-1"></div>
</div>