config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  get "users/login_form"
  post "users/login"
  post "users/logout"
  get "users/:id/active" => "users#active", as: "users_active"
  patch "users/:id/active_update" => "users#active_update", as: "users_active_update"

  get "users/:id/password_edit" => "users#password_edit", as: "users_password_edit"
  patch "users/:id/password_update" => "users#password_update", as: "users_password"

  get "users/password_forget" => "users#password_forget", as: "users_password_forget"
  post "users/email_where" => "users#email_where", as: "users_email_where"
  get "users/:id/password_forget_edit" => "users#password_forget_edit", as: "users_password_forget_edit"
  patch "users/:id/password_forget_update" => "users#password_forget_update", as: "users_password_forget_update"

  get "users/:id/likes" => "users#like_index", as: "users_likes_index"
  get "sounds/day_rank"
  get "sounds/week_rank"
  get "sounds/month_rank"
  resources :users do
  	resources :like_users, only:[:create, :destroy]
  end
  resources :sounds do
  	resources :comments, only:[:create, :destroy]
    resources :like_sounds, only:[:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our drop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Corben:700 rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header_margin"></div>
    <header class="header">
      <span class="fas1"><button class="fas"><i class="fas fa-bars"></i></button></span>
      <span class="fas2"><button class="fas"><i class="fas fa-times"></i></button></span>
        <%= link_to root_path do %>
        <img src="/drop-logo.png" class="header_log" >
        <% end %>
      <% if @current_user %>
      <ul class="header1">
        <li><%= link_to "お気に入り", users_likes_index_path(@current_user.id) %></li>
        <li><%= link_to "User一覧", users_path %></li>
        <li><%= link_to "曲一覧", sounds_path %></li>
        <li><%= link_to "曲投稿", new_sound_path %></li>
        <li><%= link_to "マイページ", user_path(@current_user.id) %></li>
        <li><%= link_to "ログアウト", users_logout_path, method: :post %></li>
      </ul>
      <% else %>
      <ul class="header1">
        <li><%= link_to "User一覧", users_path %></li>
        <li><%= link_to "曲一覧", sounds_path %></li>
        <li><%= link_to "ログイン", users_login_form_path %></li>
        <li><%= link_to "新規登録", new_user_path %></li>
      </ul>
      <% end %>
    </header>
    <div class="menu">
        <% if @current_user %>
      <ul class="media-menu">
        <li><%= link_to "お気に入り", users_likes_index_path(@current_user.id) %></li>
        <li><%= link_to "User一覧", users_path %></li>
        <li><%= link_to "曲一覧", sounds_path %></li>
        <li><%= link_to "曲投稿", new_sound_path %></li>
        <li><%= link_to "マイページ", user_path(@current_user.id) %></li>
        <li><%= link_to "ログアウト", users_logout_path, method: :post %></li>
        <li class="ask_form"><%= link_to "お問い合わせはコチラ", "https://docs.google.com/forms/d/e/1FAIpQLSeIioXvAtvzCX09QVzmpeB4LgtspsM1Ki5KYLi3gOZAgt_JsA/viewform?usp=sf_link", class: "ask_form" %></li>
      </ul>
      <% else %>
      <ul class="media-menu">
        <li><%= link_to "ログイン", users_login_form_path %></li>
        <li><%= link_to "新規登録", new_user_path %></li>
        <li><%= link_to "User一覧", users_path %></li>
        <li><%= link_to "曲一覧", sounds_path %></li>
        <li class="ask_form"><%= link_to "お問い合わせはコチラ", "https://docs.google.com/forms/d/e/1FAIpQLSeIioXvAtvzCX09QVzmpeB4LgtspsM1Ki5KYLi3gOZAgt_JsA/viewform?usp=sf_link", class: "ask_form" %></li>
      </ul>
      <% end %>
      </div>
    <div class="contents flash">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type} center") %>
      <% end %>
    </div>
    <div class="header_margin"></div>
    <div class="header_top"></div>
      <%= yield %>
      <div class="footer_top"></div>
    <footer>
      <div class="col-md-2"></div>
      <div class="col-md-8">
       <small>COPYRIGHT &#169; Our drop ALL RIGHTS RESERVED.</small>
      </div>
      <div class="col-md-2 ask_form">
        <%= link_to "お問い合わせはコチラ", "https://docs.google.com/forms/d/e/1FAIpQLSeIioXvAtvzCX09QVzmpeB4LgtspsM1Ki5KYLi3gOZAgt_JsA/viewform?usp=sf_link", class: "ask_form" %>
      </div>
    </footer>
  </body>
</html>